import turtle

# Set up the screen
screen = turtle.Screen()
screen.bgcolor("white")
turtle.colormode(255)
t = turtle.Turtle()
t.speed(5)
t.pensize(2)

# --- Draw the rectangular base ---
t.penup()
t.goto(-200, -150)
t.pendown()
t.color(100, 100, 100) # Gray color
t.begin_fill()
t.fillcolor(150, 150, 150) # Lighter gray fill
t.forward(400)
t.left(90)
t.forward(300)
t.left(90)
t.forward(400)
t.left(90)
t.forward(300)
t.left(90)
t.end_fill()

# --- Draw the shapes ---
# Square (Orange)
t.penup()
t.goto(-150, -100)
t.pendown()
t.color("orange")
t.fillcolor("orange")
t.begin_fill()
t.right(45)
t.circle(60, steps=4)
t.end_fill()

# Star (Yellow)
t.penup()
t.goto(-100, 140)
t.pendown()
t.color("yellow")
t.fillcolor("yellow")
t.begin_fill()
t.right(18)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.end_fill()

# Circle (Red)
t.penup()
t.goto(0, 0)
t.pendown()
t.color("red")
t.fillcolor("red")
t.begin_fill()
t.circle(40)
t.end_fill()

# Semicircle (Blue)
t.penup()
t.goto(50, -100)
t.pendown()
t.color("blue")
t.fillcolor("blue")
t.begin_fill()
t.circle(40, 180)
t.end_fill()

# Triangle (Green)
t.penup()
t.goto(160, 130)
t.pendown()
t.color("green")
t.fillcolor("green")
t.begin_fill()
t.circle(60, steps=3)
t.end_fill()

# --- Add a Title ---
t.penup()
t.goto(-100, 160)
t.pendown()
t.color("black")
t.write("Shape Sorter", font=("Arial", 24, "bold"))

# Keep the window open
turtle.done()